CREATE TABLE IF NOT EXISTS orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  stripe_session_id TEXT UNIQUE,
  customer_email TEXT NOT NULL,
  sender_name TEXT,
  sender_address TEXT,
  recipient_name TEXT,
  recipient_address TEXT,
  letter_type TEXT CHECK(letter_type IN ('text', 'pdf')),
  return_receipt INTEGER DEFAULT 0,
  tracking_number TEXT,
  status TEXT DEFAULT 'pending',
  amount_cents INTEGER,
  order_token TEXT UNIQUE,
  phone_number TEXT,
  scm_queue_id TEXT,
  delivery_status TEXT DEFAULT 'processing',
  delivery_status_detail TEXT,
  delivery_status_updated_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
